baseURL = "http://harmonyapp.io"
languageCode = "en-us"
title = "Harmony"
theme = "nu"

[params]
    description = "Your place. Your communities. Your friends."

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/harmony-development"
    weight = -90

  [[menu.main]]
    identifier = "trynow"
    name = "Try Now"
    url = "https://staccato.harmonychat.vercel.app"
    weight = -80
