baseURL = "http://harmonyapp.io"
languageCode = "en-us"
title = "Harmony"

[params]
    description = "Your place. Your communities. Your friends."

[markup.goldmark.renderer]
    unsafe = "true"

[menu]

  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/docs/faq"
    weight = -110

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs"
    weight = -105

  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/harmony-development"
    weight = -90

  # [[menu.main]]
  #   identifier = "trynow"
  #   name = "Try Now"
  #   url = "https://tempest.bluskript.vercel.app"
  #   weight = -80
