baseURL = "http://harmonyapp.io"
languageCode = "en-us"
title = "Harmony"

[params]
    description = "Your place. Your communities. Your friends."


[markup]
  [markup.goldmark.renderer]
      unsafe = "true"

  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1

[menu]

  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/docs/faq"
    weight = -110

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs"
    weight = -105

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = -100

  [[menu.main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/harmony-development"
    weight = -90

  # [[menu.main]]
  #   identifier = "trynow"
  #   name = "Try Now"
  #   url = "https://tempest.bluskript.vercel.app"
  #   weight = -80
